name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-22.04
    name: ${{ matrix.cmd }}
    strategy:
      fail-fast: false
      matrix:
        cmd:
          - build
          - prettier
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm install --frozen-lockfile --no-color
      - run: pnpm ${{ matrix.cmd }}
