name: Verify

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: ${{ matrix.cmd }}
    strategy:
      fail-fast: true
      matrix:
        cmd:
          - fmt --check
          - lint
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno ${{ matrix.cmd }}
